### ISSUE TITLE
Not working in a docker container

### ISSUE THREAD

**Issue by ArtieFuzzz** [TMWare/status-rotate#178]
## Bug Description

@tmware/status-rotate not working inside a docker container

### Did this behavior use to work in the previous version?

Yes, this bug was not present in the previous version

## Steps to Reproduce

1. Create a bot
2. Create a Dockerfile just like [this](https://github.com/AstraeaStudios/Astraea/blob/main/Dockerfile)
3. Setup status-rotate as normal
4. Run the docker image

## Logs

- Error output: ![What brings you here?](https://typescript.is-ne.at/55Rg9EHR4.png)

## System Information

- Application Version: 1.2.6
- Node.js Version: v16
- Platform / Operating system: Linux (Docker)

**Comment by TMUniversal** [comment]
Problem was not on @tmware/status-rotate,
see https://github.com/AstraeaStudios/Astraea/pull/7
